---
title: "vpa_exp_pathway"
author: "Darya Akimova"
date: "12/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup

## Packages

```{r packages, comment=NA}
library(tidyverse)
library(GGally)
```


# Data

```{r data, comment=NA}
vpa.cmpnd.info.raw <- paste(
  "./data/compound_info/vpa_only_exp1/", 
  list.files(path = "./data/compound_info/vpa_only_exp1"), 
  sep = ""
  ) %>% 
  map(read_csv)
vpa.hits.raw <- paste(
  "./data/hit_lists/vpa_only_exp1/", 
  list.files(path = "./data/hit_lists/vpa_only_exp1/"), 
  sep = ""
  ) %>% 
  map(read_csv)
# compound info
cmpnd.id <- read_csv("./data/other/anp_db_compound_kegg_fixed.csv")
kegg.info <- read_csv("./data/other/kegg_pathways_updated.csv")
filtered.pathways <- read_csv("./data/other/filtered_list_of_pathways.csv")
```


# Cleanup

```{r comment=NA}
vpa.cmpnd.info.prep <- vpa.cmpnd.info.raw %>% 
  bind_rows() %>% 
  mutate(
    mode = ifelse(
      str_detect(compound_short, "VPAnC"), "cell.neg", 
      ifelse(
        str_detect(compound_short, "VPApC"), "cell.pos", 
        ifelse(
          str_detect(compound_short, "VPAnM"), "med.neg", "med.pos"
          )
        )
      )
    ) 
table(vpa.cmpnd.info.prep$mode)
vpa.hits.prep <- vpa.hits.raw %>% 
  bind_rows() %>%
  mutate(
    mode = ifelse(
      str_detect(compound_short, "VPAnC"), "cell.neg", 
      ifelse(str_detect(compound_short, "VPApC"), "cell.pos", "med.neg")
      )
    )
table(vpa.hits.prep$mode)
colnames(kegg.info) <- c("KEGG", str_to_lower(colnames(kegg.info))[2:length(colnames(kegg.info))])
kegg.info <- kegg.info %>% 
  select(-c(reaction:brite))
kegg.info
```


# DB Merges

```{r db_merges, comment = NA}
vpa.cmpnd.info.prep %>% 
  inner_join(cmpnd.id, by = "cas_id", suffix = c("_exp", "_db")) %>% 
  anti_join(kegg.info, by = "KEGG") %>% 
  {table(.$KEGG)}
vpa.hits.prep %>% 
  inner_join(cmpnd.id, by = "cas_id", suffix = c("_exp", "_db")) %>% 
  anti_join(kegg.info, by = "KEGG") %>% 
  {table(.$KEGG)}
vpa.full.cmpnd.join <- vpa.cmpnd.info.prep %>% 
  inner_join(cmpnd.id, by = "cas_id", suffix = c("_exp", "_db")) %>% 
  left_join(kegg.info, by = "KEGG", suffix = c("_data", "_kegg"))
vpa.hits.join <- vpa.hits.prep %>% 
  inner_join(cmpnd.id, by = "cas_id", suffix = c("_exp", "_db")) %>% 
  left_join(kegg.info, by = "KEGG", suffix = c("_data", "_kegg"))
vpa.full.cmpnd.join %>% 
  select(mass, mol_weight, exact_mass) %>% 
  ggpairs()
vpa.full.cmpnd.join %>% 
  ggplot(aes(mass, exact_mass)) +
  geom_point()
vpa.full.cmpnd.join %>% 
  filter(exact_mass > mass + 20)
# found the form without phosphate
colnames(vpa.full.cmpnd.join)
vpa.full.pathways <- vpa.full.cmpnd.join %>% 
  select(compound_short, compound_full_exp, mode, cas_id, KEGG, pathway) %>% 
  separate(pathway, into = paste("pathway", 1:55, sep = "_"), sep = ";") %>% 
  gather("path_num", "path_name", -c(compound_short:KEGG)) %>% 
  filter(!(is.na(path_name))) %>% 
  select(-path_num) %>% 
  distinct()
vpa.hits.pathways <- vpa.hits.join %>% 
  select(compound_short, compound_full_exp, mode, cas_id, KEGG, pathway) %>% 
  separate(pathway, into = paste("pathway", 1:55, sep = "_"), sep = ";") %>% 
  gather("path_num", "path_name", -c(compound_short:KEGG)) %>% 
  filter(!(is.na(path_name))) %>% 
  select(-path_num) %>% 
  distinct()
vpa.pathway.counts <- vpa.full.pathways %>% 
  select(-c(compound_short, mode)) %>% 
  distinct() %>% 
  group_by(path_name) %>% 
  summarize(
    tot_compnd = n()
  ) %>% 
  full_join(
    vpa.hits.pathways  %>% 
      select(-c(compound_short, mode)) %>% 
        distinct() %>% 
        group_by(path_name) %>% 
        summarize(
          tot_hits = n()
          ), 
    by = "path_name"
    ) %>% 
  arrange(desc(tot_hits)) 
vpa.pathway.counts[is.na(vpa.pathway.counts$tot_hits), "tot_hits"] <- 0

vpa.pathway.counts %>% 
  ggplot(aes(tot_compnd, tot_hits)) +
  geom_abline(intercept = 0, slope = 1) +
  geom_point(size = 2, alpha = 0.3) +
  theme_minimal() +
  xlab("Total number of compounds detected in pathway") +
  ylab("Total number of hits in pathway")
#write_csv(vpa.pathway.counts, path = "./results/vpa_exp_pathway_count.csv")
vpa.pathway.counts %>% 
  filter(path_name %in% filtered.pathways$Pathway) %>% 
  ggplot(aes(tot_compnd, tot_hits)) +
  geom_abline(intercept = 0, slope = 1) +
  geom_point(size = 2, alpha = 0.3) +
  theme_minimal() +
  xlab("Total number of compounds detected in pathway") +
  ylab("Total number of hits in pathway")

```

Select only the interesting/relevant KEGG pathways

```{r}
vpa.full.pathways %>% 
  filter(path_name %in% filtered.pathways$Pathway)
vpa.hits.pathways %>% 
  filter(path_name %in% filtered.pathways$Pathway)
vpa.pathway.counts.filtered <- vpa.pathway.counts %>% 
  filter(path_name %in% filtered.pathways$Pathway) %>% 
   mutate(percent_hits = tot_hits * 100 / tot_compnd)
#write_csv(vpa.pathway.counts.filtered, path = "./results/vpa_only_exp1/vpa_exp_pathway_count_filt.csv")
vpa.pathway.counts.filtered %>% 
  ggplot(aes(tot_compnd, percent_hits)) +
  geom_abline(intercept = 0, slope = 1) +
  geom_point(size = 2, alpha = 0.6)
vpa.hits.pathways.filt <- vpa.hits.pathways %>% 
  filter(path_name %in% filtered.pathways$Pathway)
#write_csv(vpa.hits.pathways.filt, path = "./results/vpa_only_exp_hits_pathways.csv")
vpa.full.pathways.filt <- vpa.full.pathways %>% 
  filter(path_name %in% filtered.pathways$Pathway)
#write_csv(vpa.full.pathways.filt, path = "./results/vpa_only_exp_all_cmpnd_pathways.csv")
```

